force {
  data-source-name    = "GitHubEvents"
  broadcast-data-name = "BroadcastData"

  data-dir   = "src/main/resources/data"
  partitions = [0, 1, 2, 3]

  join-keys = [
    { left-field = "actor", right-field = "login" },
    { left-field = "repo",  right-field = "name"  }
  ]

  broadcast {
    # Required by BroadcastData.load()
    users-file = "src/main/resources/broadcast/users.json"
    orgs-file  = "src/main/resources/broadcast/orgs.json"
  }
}

akka {
  actor {
    provider = "cluster"
  }
  remote {
    artery {
      canonical {
        hostname = "127.0.0.1"
        port     = 2551
      }
    }
  }
  cluster {
    seed-nodes = [
      "akka://DistribuQuerySystem@127.0.0.1:2551"
    ]
    auto-down-unreachable-after = 10s
  }
  loglevel = "INFO"
  stdout-loglevel = "INFO"
  logging-filter = "akka.event.DefaultLoggingFilter"
}

kamon {
  environment {
    service = "DistribuQuerySystem"
  }
  apm.api-key = "dg9vqfg115tnaa5hs2r9rba0ig"

  metric {
    tick-interval = 10 seconds
  }

  prometheus {
    embedded-server {
      hostname = "0.0.0.0"
      port = 9095
    }
  }
}