force {
  data-source-name    = "GitHubEvents"
  broadcast-data-name = "BroadcastData"

  input-file = "src/main/resources/dataset.json"
  worker-count = 4

  partitions = [0, 1, 2, 3]

  join-keys = [
    { left-field = "actor", right-field = "login" },
    { left-field = "repo",  right-field = "name"  }
  ]
}

akka {
  actor {
    provider = "cluster"
  }
  remote {
    artery {
      canonical {
        hostname = "127.0.0.1"
        port     = 2551
      }
    }
  }
  cluster {
    seed-nodes = [
      "akka://DistribuQuerySystem@127.0.0.1:2551"
    ]
    auto-down-unreachable-after = 10s
  }
  loglevel = "INFO"
}
